### PR TITLE
Fix for position on re-enable

### PR DESCRIPTION
**Pull request by DFliyerz**
Right now when you disable the prop while it's in a position that wasn't the reset position then re-enable it, the prop will remain in  the old position for one frame before snapping back to the reset position. This can cause issues if the prop has a sender on it since it can send the signal right after it spawns if the old position would cause it to send a signal. As for why the file is so much smaller, the old file seems to have a ton of extra keyframes for some reason.

### CODE REVIEW

**Comment by ThatFatKidsMom** [comment]
Those frames are there for consistency by ensuring that the prop properly resets its position exactly where the reset position game object is when turning off the system. Without them and in your current iteration the prop will maintain its relative offsets from where the root bone was last constrained to. For example if the prop was left 2 meters below the root bone and you turn the system off it will maintain that offset when turning it back on. In game that would mean the prop would spawn 2 meters below from where the reset position is resulting in it being likely under the map and hidden from view. The same would apply with any other direction so rather than the prop being exactly at the reset point, the prop will be offset in some other direction from the reset point.

**Comment by DFliyerz** [comment]
That's odd, because I wasn't seeing any offsets with the fix I had at least in Unity with the avatar emulator. Additionally, the error with the prop appearing at it's old position for a frame before returning to the reset position was only happening on the 2nd instance of being despawned and spawned. I'll test it in game and see if my fix breaks anything, and if it does I'll try to find another workaround.

**Comment by ThatFatKidsMom** [comment]
After taking another look at your modified animation file, it seems you are using an older version of the prefab based on the missing keys and use of scale rather than rotation for handling prop orientation in different hands. The latter being changed in release 1.0.2 so you may have an even older version than that. The current release is 1.0.3.

**Comment by DFliyerz** [comment]
Thanks for the catch, I'll update my version. I'll trust you on the "fix" I did causing issues, since I think I can find some other ways to fix the problem.

**Comment by DFliyerz** [comment]
Turns out updating fixed the issue anyways, so no need for my other methods. There's a couple of other bugs that I'm running into but I'm guessing it's just related to the prop system not being super stable, I'll make issues if I can get them reproducible.

**Pull request closed without merging**
